### ISSUE TITLE
videocast script

### ISSUE THREAD

**Issue by dryanmas** [req-dot-body/scratch-track#448]

**Comment by npoling** [comment]
//Show landing screen and then navigate to project view

As a busy musician on the go, you never know when inspiration will strike, and genius ideas don’t last for long.  You could scribble that riff down on a bar napkin, write up some lyrics in your smart phone, or sing a few bars on your bandmate’s voicemail.  

//Begin making a new demo project

But now you have ScratchTrack.

//Quickly lay down a new track and show recording process w/lyrics and tabs

ScratchTrack allows you to keep your song-writing workflow organized and minimizes the barriers to you maximizing your creativity.  When inspiration strikes, open up a new project,  jot down some lyrics, easily tab out a riff, and then record a rough cut with a single tap or click.  Keep project resources all in one easy to find place, share your progress with your collaborators, and quickly revise lyrics, tabs, and rough cuts as your ideas evolve.

ScratchTrack is designed for rapidly iterating on your ideas so that you can maintain a flexible, fluid creative process while still maintaining project resources in organized, coherent form.  Even the most loosely formed chorus or riff can easily be rendered as high-quality, easy-to-read tablature.

ScratchTrack: Songwriting as it should be.
